-- create the user
CREATE USER CLINICAUNA
  IDENTIFIED BY UNA
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;

-- grant/revoke role privileges
GRANT RESOURCE TO CLINICAUNA;

GRANT CONNECT TO CLINICAUNA;

GRANT DBA TO CLINICAUNA;

-- grant/revoke system privileges
GRANT CREATE SESSION TO CLINICAUNA;

GRANT UNLIMITED TABLESPACE TO CLINICAUNA;