-- Activate the user
CREATE OR REPLACE PROCEDURE ACTIVATE_USER (
    USER_ID IN NUMBER
) AS
BEGIN
    UPDATE TBL_USER
    SET
        ISACTIVE = 'Y'
    WHERE
        ID = USER_ID;
    COMMIT;
END ACTIVATE_USER;