-- Change the password
CREATE OR REPLACE PROCEDURE CHANGE_PASSWORD (
    USER_ID IN NUMBER,
    NEW_PASSWORD IN VARCHAR2,
    CHANGED_PASSWORD OUT VARCHAR2
) AS
BEGIN
    UPDATE TBL_USER
    SET
        PASSWORD = NEW_PASSWORD,
        PASSWORDCHANGED = 'Y'
    WHERE
        ID = USER_ID;
    COMMIT;
END CHANGE_PASSWORD;